### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by rkreutz**
Hey there,

I've noticed there was a PR adding Carthage support but was using Cocoapods instead of Carthage to install the dependencies, so now I've opened a PR with different configuration so it uses entirely Carthage.

Only thing missing once merging this would be to make a new tag with these changes introduced, otherwise Carthage will try to use version 2.0.2 which wasn't compatible yet.

You can test this out on my fork, version `2.0.4` there should be working with Carthage.

### CODE REVIEW

**Comment by lachlanbell** [comment]
Thank you! Looks great at a first glance, although we will need to keep `Podfile` as it's still needed to pull in the CryptoSwift dependency for CocoaPods users.

I'll merge this once I've had the chance to properly test it. Thanks again for your efforts

**Comment by rkreutz** [comment]
From what I know of cocoapods, all you need is the `podspec` file, the Podfile in that context was really for the library project to compile while editing the source code, right now it is working but instead of using Cocoapods it is using Carthage. I based my work on some other famous libraries that also have nested dependencies (namely https://github.com/RxSwiftCommunity/RxSwiftExt) which in general don't have a Podfile

**Comment by rkreutz** [comment]
Just to give you an update on this one, I've tried using my fork as a dependency on another project using:
```ruby
pod 'SwiftOTP', :git => 'https://github.com/rkreutz/SwiftOTP.git', :tag => '2.0.5'
```
And it worked fine, it was able to add the library as Cocoapods dependency

**Comment by lachlanbell** [comment]
Ah, thanks for testing that. Everything seems to work fine, I'll merge. Cheers!

**Pull request merged**
