### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by GuillermoCiqueHolvi**
This adds Carthage support, might not be the cleanest way of doing this but I can't find what that way would look like. At least this is working and should not affect CocoaPods support.

### CODE REVIEW

**Comment by lachlanbell** [comment]
Awesome, thanks for your work! I'll take a look

**Comment by javierHolvi** [comment]
It will be great to have Carthage support.

**Comment by GuillermoCiqueHolvi** [comment]
I don't think it would because Carthage needs to be able to compile this without anything else. I don't think there is a way of updating pods before Carthage does a build 😕

**Comment by GuillermoCiqueHolvi** [comment]
It looks like you are supporting Swift Package Manager already, this might not even be necessary once Xcode 11 comes out officially.

**Comment by rkreutz** [comment]
I've opened a new PR (#24) for this without relying on Cocoapods, I'd recommend closing this one

**Comment by lachlanbell** [comment]
Added in #24. Thanks Guillermo and Rodrigo for your efforts.

**Pull request closed without merging**
